auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_listen_address: 127.0.0.1
  http_listen_address: 127.0.0.1
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
#      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h




query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 1000

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  encoding: protobuf


limits_config:
  retention_period: 2160h
  max_query_series: 100000
  max_query_parallelism: 100
  allow_structured_metadata: false
  max_query_length: 7d
  max_query_lookback: 2d

analytics:
  reporting_enabled: false