{
 "title": "Template",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "brand",
    "query": {}
   },
   { "name": "search", "label": "search" },
   {
    "name": "AggregateBy",
    "label": "Aggregate for Top 10",
    "query": "ip,method,request_uri,status_code,referrer,user_agent"
   }
  ]
 },
 "panels": [
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(count_over_time({log_type=\"web_access\", brand=\"$brand\"} | pattern `<ip> - - [<time> <zone>]<_>\"<method> <request_uri> <http_version>\" <status_code> <bytes> \"<referrer>\" \"<user_agent>\"` [$__range])) by ($AggregateBy)))"
    }
   ]
  },
  {
   "title": "HTTP Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time({log_type=\"web_access\"} | pattern `<_> - - <_> \"<method> <_> <_>\" <status> <_> <_> \"<_>\" <_>` [1m])) by (status)"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by () (sum_over_time(({log_type=\"web_access\", brand=\"$brand\"} | pattern `<_> - - <_> \"<_>\" <_> <bytes> \"<_>\" \"<_>\"` | unwrap bytes)[1m]))"
    }
   ]
  },
  {
   "title": "Magento Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exception log",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{log_type=\"exception\", brand=\"$brand\"} |~ \"(?i)$search\""
      }
     ]
    },
    {
     "title": "System log",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{log_type=\"system\", brand=\"$brand\"} |~ \"(?i)$search\""
      }
     ]
    },
    {
     "title": "Magento reports",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{log_type=\"report\", brand=\"$brand\"} |~ \"(?i)$search\" | json | line_format \"{{.report_id}}\""
      }
     ]
    }
   ]
  },
  {
   "title": "Services Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Access",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{log_type=\"web_access\", brand=\"$brand\"} |~ `(?i)$search`"
      }
     ]
    },
    {
     "title": "HTTP Errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "{log_type=\"web_error\", brand=\"$brand\"} |~ \"(?i)$search\""
      }
     ]
    }
   ]
  }
 ]
}