{
 "title": "Wordpress",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "brand",
    "query": {}
   },
   { "name": "search", "label": "search" },
   { "name": "exclude", "label": "exclude", "query": "Exclude: info or INFO|warning" },
   {
    "name": "AggregateBy",
    "label": "Aggregate for Top 10",
    "query": "ip,method,request_uri,status_code,referrer,user_agent"
   }
  ]
 },
 "panels": [
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(count_over_time({log_type=\"web_access\", brand=\"$brand\"} | pattern `<ip> <_> <_> [<time> <zone>] \"<method> <request_uri> <http_version>\" <status_code> <bytes> \"<referrer>\" \"<user_agent>\"` | status_code!=\"403\" [$__range])) by ($AggregateBy)))"
    }
   ]
  },
  {
   "title": "HTTP Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({log_type=\"web_access\", brand=\"$brand\"} | pattern `<_> <_> <_> <_> \"<_> <_> <_>\" <status> <_> <_> \"<_>\" <_>` [1m]))"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by () (sum_over_time(({log_type=\"web_access\", brand=\"$brand\"} | pattern `<_> - - <_> \"<_>\" <_> <bytes> \"<_>\" \"<_>\"` | unwrap bytes)[1m]))"
    }
   ]
  },
  {
   "title": "Wordpress Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "WC logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "{log_type=\"wc-logs\", brand=\"$brand\"} |~ \"(?i)$search\" !~ `((?i)$exclude)`"
      }
     ]
    }
   ]
  },
  {
   "title": "Services Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Access",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{log_type=\"web_access\", brand=\"$brand\"} |~ `(?i)$search` !~ `((?i)$exclude)`"
      }
     ]
    },
    {
     "title": "HTTP Errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "{log_type=\"web_error\", brand=\"$brand\"} |~ \"(?i)$search\" !~ `((?i)$exclude)`"
      }
     ]
    },
    {
     "title": "PHP-FPM logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "{log_type=\"phpfpm\", brand=\"$brand\"} |~ \"(?i)$search\" !~ `((?i)$exclude)`"
      }
     ]
    }
   ]
  }
 ]
}